# This is a basic workflow to help you get started with Actions

- name: SSH Server Deploy
  # You may pin to the exact commit or the version.
  # uses: kostya-ten/ssh-server-deploy@e0deb814bc458a68b61f6597a865d096e33eb586
  uses: kostya-ten/ssh-server-deploy@v4
  with:
    # Host
    host: 
    # Port
    port: # optional, default is 22
    # Username
    username: 
    # Password
    password: # optional
    # Private key
    private_key: # optional
    # Before script
    before_script: # optional
    # After script
    after_script: # optional
    # After script
    scp_source: # optional
    # After script
    scp_target: # optional, default is ~
